v1: "/api/v1"
endpoints:
  documents:
    upload: "document/upload"
    documents: "documents"
  system_settings:
    remove-documents: "system/remove-documents"
  workspaces:
    update-embeddings: "workspace/{slug}/update-embeddings"
    new: "workspace/new"
    delete: "workspace/{slug}"
