v1: "/api/v1"
endpoints:
  admin:
    delete: "admin/users/{id}"
    manage-users: "admin/workspaces/{workspaceSlug}/manage-users"
    new: "admin/users/new"
    users: "admin/users"
    ws-users: "admin/workspaces/{workspaceId}/users"
  documents:
    documents: "documents"
    upload: "document/upload"
  system_settings:
    remove-documents: "system/remove-documents"
  workspaces:
    delete: "workspace/{slug}"
    new: "workspace/new"
    update-embeddings: "workspace/{slug}/update-embeddings"
