v1: "/api/v1"
endpoints:
  admin:
    users: "admin/users"
  documents:
    documents: "documents"
    upload: "document/upload"
  system_settings:
    remove-documents: "system/remove-documents"
  workspaces:
    delete: "workspace/{slug}"
    new: "workspace/new"
    update-embeddings: "workspace/{slug}/update-embeddings"
